# -*- coding: utf-8 -*-
"""Quiz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pge_hCw7N3lPtnhKK0LuIZw5rQulypuv
"""

# Interactive Command Tutor Script — Eta Team
# Colored Version

# ANSI color codes
GREEN = "\033[92m" #sets text color to green
RED = "\033[91m" #sets text color to red
RESET = "\033[0m" #resets color back to default color so nexct text isnt colored

questions = [ #created a list of dictionaries
    {#each element is a dictionary containing key-value pairs
        "question": "1. What does pwd do?",
        "options": [ #each option elements holds another list of strings
            "a. Changes directory",
            "b. Tells you the current directory you’re in",
            "c. Tells you which user you are",
            "d. Makes a new directory"
        ],
        "answer": "b"
    },

    {
        "question": "2. Which one makes a nested directory Parent/Child?",
        "options": [
            "a. mkdir -p Parent/Child",
            "b. mkdir Parent && mkdir Child",
            "c. mkdir Parent/Child",
            "d. rmdir Parent/Child"
        ],
        "answer": "a"
    },

    {
        "question": "3. Where does the locate command search?",
        "options": [
            "a. Searches inside binary files",
            "b. Searches within a text file for a word",
            "c. Searches the whole operating system",
            "d. Searches in a specific directory"
        ],
        "answer": "c"
    },

    {
        "question": "4. Which is the correct way to find the vowels in a file?",
        "options": [
            "a. grep -E \"^[aeiou]\"",
            "b. grep \"aeiou\"",
            "c. grep -E \"$[aeiou]\"",
            "d. grep -E \"aeiou\""
        ],
        "answer": "a"
    },

    {
        "question": "5. How to append using cat?",
        "options": [
            "a. cat > file.txt",
            "b. cat file.txt",
            "c. cat >> file.txt",
            "d. All of the above"
        ],
        "answer": "c"
    },

    {
        "question": "6. Which one changes the execution permission for the user?",
        "options": [
            "a. chmod",
            "b. chmod u+w",
            "c. chmod u+r",
            "d. chmod u+x"
        ],
        "answer": "d"
    },

    {
        "question": "7. Which command searches for the occurrences of a file and changes it permanently?",
        "options": [
            "a. sed -i",
            "b. awk",
            "c. pwd",
            "d. sed"
        ],
        "answer": "a"
    },

    {
        "question": "8. You can remove a non-empty directory using rmdir?",
        "options": [
            "a. True",
            "b. False"
        ],
        "answer": "b"
    },

    {
        "question": "9. Piping means the output of one command is the input of another one using '|'.",
        "options": [
            "a. True",
            "b. False"
        ],
        "answer": "a"
    },

    {
        "question": "10. The command sort -r file.txt reverses each letter in the words of a file.",
        "options": [
            "a. True",
            "b. False"
        ],
        "answer": "b"
    },

    {
        "question": "11. Crontab is used to schedule automated tasks.",
        "options": [
            "a. True",
            "b. False"
        ],
        "answer": "a"
    },

    {
        "question": "12. tar -czvf is used to extract an archived file.",
        "options": [
            "a. True",
            "b. False"
        ],
        "answer": "b"
    },

    {
        "question": "13. Choose the command that prints the row 3 of system.txt",
        "options": [
            "a. awk 'NR==3' system.txt",
            "b. awk '{print $3}' system.txt",
            "c. awk 'NF==3' system.txt",
            "d. awk '{NR==3}' system.txt"
        ],
        "answer": "a"
    },

    {
        "question": "14. Choose the command that prints the number of lines in file.txt",
        "options": [
            "a. wc file.txt",
            "b. -l file.txt",
            "c. nl file.txt",
            "d. wc -l -w -m file.txt"
        ],
        "answer": "c"
    },

    {
        "question": "15. What is the command used to extract a section from a text?",
        "options": [
            "a. grep",
            "b. awk",
            "c. cut",
            "d. sed"
        ],
        "answer": "c"
    },

    {
        "question": "16. Which command is used to display previous commands typed in the terminal?",
        "options": [
            "a. clear",
            "b. history",
            "c. pwd",
            "d. whoami"
        ],
        "answer": "b"
    },

    {
        "question": "17. Which command is used to search for running processes by name?",
        "options": [
            "a. pgrep",
            "b. grep",
            "c. sort",
            "d. chmod"
        ],
        "answer": "a"
    },

    {
        "question": "18. Which command removes duplicate lines while sorting?",
        "options": [
            "a. sort -r",
            "b. sort -n",
            "c. sort -u",
            "d. sort -k"
        ],
        "answer": "c"
    },

    {
        "question": "19. In a crontab entry '30 2 * * 1-5 /root/script', when does it run?",
        "options": [
            "a. Every 30 minutes all day",
            "b. At 2:30 AM, Monday through Friday",
            "c. At 2:30 PM every day",
            "d. On the 30th of every month at 2 AM"
        ],
        "answer": "b"
    },

    {
        "question": "20. Which command shows your machine's IP address?",
        "options": [
            "a. ipconfig",
            "b. netstat",
            "c. ifconfig",
            "d. ping"
        ],
        "answer": "c"
    }
]

score = 0 #initializees score to zero to keep track of points

print("=" * 50) #prints '=' 50 times just to visually seperate from the list of questions
print(" Welcome to the Interactive Command Tutor ")
print("               Eta Team")
print("=" * 50)

for q in questions: #loop that iterates over evert dictionary (q) inside the questions list

    print("\n" + q["question"]) #prints a space then accesses the value related to the questions key in the current dictionary

    for option in q["options"]: #loop that will iterate through the list of strings stored in the options key for teh current questions
        print(option) #will print all options (a,b,c,d) on a new line
    while True: #while loop that ensures user input is only a,b,c,d and won't stop until the code hits a break statement.
        user_answer = input("Enter your answer (a/b/c/d): ").lower().strip()#prompts the user to type their answer and stores it in variable user_answer
                                                                 #.lower() concerts input to lowercase to match the answer key
                                                                 #.strip() removes any accidental spaces the user might hit before or after their letter.
        # checks if the input is in a list of valid options
        if user_answer in ['a', 'b', 'c', 'd']: #uses the in operator to check if the user input exists in our list of options
            break  #this exits the 'while' loop to grade answer
        else:
            print(RED + " Invalid input! Please choose only a, b, c, or d." + RESET) #will keep printing this message if input invalid

    if user_answer == q["answer"]: #checks if the user's answer matches the value stored in the answer key

        # prints the correct answer in green and then resets the color
        print(GREEN + " Correct!" + RESET)

        score += 1 #increments the score by 1 for every right answer

    else: #if answer doesn't match value in asnwer key

        # prints the wrong answer in red and uses an f-string to insert the correct answer and then resets the color
        print(RED + f" Wrong! Correct answer is {q['answer']}" + RESET)

print("\n" + "=" * 50)
print(f"Final Score: {score}/{len(questions)}") #prints the final score out of the total number of questions

